version: '3.2'

services:
  frontend:
    image: frontend-react
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/copy/k6e203.p.ssafy.io:/var/www/html
    container_name: "frontend"

  backend:
    image: backend-spring
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    volumes:
      - /etc/letsencrypt/copy/k6e203.p.ssafy.io:/root
    container_name: "backend"

  # flask:
  #   image: flask
  #   build:
  #     context: flask_server/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - /etc/letsencrypt/copy/k6e203.p.ssafy.io:/root
  #   container_name: "flask"